[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
core_log = { path = "../core/log" }

bevy = { workspace = true }
bevy_egui = { workspace = true }
bevy_renet = { workspace = true }
egui = { workspace = true }