[workspace]
resolver = "2"
members = [
    "client",
    "server",
]

[workspace.dependencies]
# Основной framework игрового движка.
bevy = { version = "0.14" }

# TODO включить оптимизации после возникновения проблем с производительностью
[profile.dev]
opt-level = 0

# TODO включить оптимизации после возникновения проблем с производительностью
[profile.dev.package."*"]
opt-level = 0