[package]
name = "feature_network_server"
version = "0.1.0"
edition = "2021"

[dependencies]
feature_network_shared = { path = "../shared" }

bevy = { workspace = true }
bevy_renet = { workspace = true }