[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
core_log = { path = "../core/log" }
core_network_server = { path = "../core/network/server" }

bevy = { workspace = true }
bevy_renet = { workspace = true }