[package]
name = "core_network_server"
version = "0.1.0"
edition = "2021"

[dependencies]
core_network_shared = { path = "../shared" }
core_loading = { path = "../../loading" }

bevy = { workspace = true }
bevy_renet = { workspace = true }