[package]
name = "feature_sync_player_position_server"
version = "0.1.0"
edition = "2021"

[dependencies]
core_network_server = { path = "../../../core/network/server" }
feature_sync_player_position_shared = { path = "../shared" }

bevy = { workspace = true }
bevy_renet = { workspace = true }
