[package]
name = "core_players_client"
version = "0.1.0"
edition = "2021"

[dependencies]
core_players_shared = { path = "../shared" }
core_network_client = { path = "../../../core/network/client" }


bevy = { workspace = true }
bevy_renet = { workspace = true }
bincode = { workspace = true }
