name: ci

on:
  push:
    branches:
      - master


jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: >-
          sudo apt-get install -y
          libasound2-dev
          portaudio19-dev
          build-essential
          libpulse-dev
          libdbus-1-dev
          libudev-dev

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release