name: ci

on:
  push:
    branches:
      - master


jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: >-
          sudo apt-get install -y
          libasound2-dev
          portaudio19-dev
          build-essential
          libpulse-dev
          libdbus-1-dev
          libudev-dev

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install rust wasm-bindgen
        run: cargo install -f wasm-bindgen-cli

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Build project wasm
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown

      - name: Run wasm-bindgen
        run: wasm-bindgen --out-dir ./out/ --target web ./target/wasm32-unknown-unknown/release/tech_and_magic.wasm

      - name: Archive site for github pages
        run: >-
          tar
          --directory "./out/"
          -cvf "tech_and_magic_wasm.tar"
          .

      - name: Upload github pages
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./tech_and_magic_wasm.tar


  deploy:
    #See: https://github.com/actions/deploy-pages
    name: deploy
    needs: build
    runs-on: ubuntu-22.04

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1